---
- name: Create a hello-world 
  hosts: workers
  roles:
    - common

  tasks:
    - name: Create a file Called '/tmp/testfile'
      copy: 
        content: hello world
        dest: /tmp/testfile
    
  