- name: check spark directory 
  file:
    path: "{{ item }}"
    state: directory 
    mode: 0755 
  with_items: 
    - "{{ spark_src_dir }}"
    - "{{ spark_install_dir }}"

- name: Download Spark 
  get_url:
    dest: "{{ spark_src_dir }}" 
    url: "{{ spark_url }}" 
    force: no
      
- name: Extract spark 
  unarchive:
    src: "{{ spark_src_dir + '/' + spark_file }}"
    dest: "{{ spark_install_dir }}"
    remote_src: yes

- name: Link to current spark 
  file: 
    state: link 
    src: "{{ spark_install_dir/spark-spark_version-bin-hadoop2.7 }} "
    dest: /usr/local/spark 